// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RHLightResponseCostC
NumericVector RHLightResponseCostC(NumericVector theta, NumericVector flux, NumericVector sdFlux, NumericVector parameterPrior, NumericVector sdParameterPrior, NumericVector Rg, NumericVector VPD, NumericVector Temp, NumericVector VPD0, LogicalVector fixVPD);
RcppExport SEXP _REddyProc_RHLightResponseCostC(SEXP thetaSEXP, SEXP fluxSEXP, SEXP sdFluxSEXP, SEXP parameterPriorSEXP, SEXP sdParameterPriorSEXP, SEXP RgSEXP, SEXP VPDSEXP, SEXP TempSEXP, SEXP VPD0SEXP, SEXP fixVPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type flux(fluxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdFlux(sdFluxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameterPrior(parameterPriorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdParameterPrior(sdParameterPriorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Rg(RgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VPD(VPDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Temp(TempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type VPD0(VPD0SEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type fixVPD(fixVPDSEXP);
    rcpp_result_gen = Rcpp::wrap(RHLightResponseCostC(theta, flux, sdFlux, parameterPrior, sdParameterPrior, Rg, VPD, Temp, VPD0, fixVPD));
    return rcpp_result_gen;
END_RCPP
}
// whichValueGreaterEqualC
IntegerVector whichValueGreaterEqualC(IntegerVector x, IntegerVector threshold, IntegerVector iStart);
RcppExport SEXP _REddyProc_whichValueGreaterEqualC(SEXP xSEXP, SEXP thresholdSEXP, SEXP iStartSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type iStart(iStartSEXP);
    rcpp_result_gen = Rcpp::wrap(whichValueGreaterEqualC(x, threshold, iStart));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_REddyProc_RHLightResponseCostC", (DL_FUNC) &_REddyProc_RHLightResponseCostC, 10},
    {"_REddyProc_whichValueGreaterEqualC", (DL_FUNC) &_REddyProc_whichValueGreaterEqualC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_REddyProc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
