# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RHLightResponseCostC <- function(theta, flux, sdFlux, betaPrior, sdBetaPrior, Rg, VPD, Temp, E0, VPD0, fixVPD) {
    .Call('REddyProc_RHLightResponseCostC', PACKAGE = 'REddyProc', theta, flux, sdFlux, betaPrior, sdBetaPrior, Rg, VPD, Temp, E0, VPD0, fixVPD)
}

whichValueGreaterEqualC <- function(x, threshold, iStart) {
    .Call('REddyProc_whichValueGreaterEqualC', PACKAGE = 'REddyProc', x, threshold, iStart)
}

