#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+++ R script for deleting debugging code +++
#+++ Code used only for debugging can be written inside dummy functions .tmp.f().
#+++ With this script, these functions will be deleted on loading or sourcing the package.
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Remove debugging code that is encapsulated in .tmp.f function blocks (to prevent R check complaints)
.tmp.f <- NULL

# Prevent R CMD check on complaining of unused bindings
if (getRversion() >= "2.15.1") {
	# used in magitr and classes
	utils::globalVariables(c(".", ".self"))
	# used in sEddyProc with <<-
	utils::globalVariables(c("sID", "sDATA", "sINFO", "sLOCATION", "sTEMP", "sUSTAR"))
}

# if (getRversion() >= "3.1.0") {
# 	utils::suppressForeignCheck(c("sID", "sDATA", "sINFO", "sLOCATION", "sTEMP", "sUSTAR")
# 	                              , package = "REddyProc")
# }

# used in sEddyProc methods with <<-
# workaround: define global variables
# do not want to generate Rd files, unfortunately with assign also Rd files are generated by inlinedocs
sID <- sDATA <- sINFO <- sLOCATION <- sTEMP <- sUSTAR <- "globalsREddyProcDummyToSatisfyRCMDcheck"

